import { MaterialCommunityIcons } from "@expo/vector-icons";
import { useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, Pressable, Text, TextInput, View } from "react-native";

import { EmptyState, Header, PrimaryButton, Screen, SectionTitle, sharedStyles } from "@/src/components/screen";
import { type Position, useApp } from "@/src/store";
import { makeStyles, useTheme } from "@/src/theme";

const positions: Position[] = ["Portero", "Cierre", "Ala", "Pívot"];

export default function AdminScreen() {
  const { state, cloudStatus, isAdmin, addPlayer, removePlayer, resetSeason, loginAdmin, logoutAdmin } = useApp();
  const { colors } = useTheme();
  const styles = useStyles();
  const [name, setName] = useState("");
  const [number, setNumber] = useState("");
  const [position, setPosition] = useState<Position>("Ala");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const add = () => { if (!name.trim() || !number.trim()) { Alert.alert("Faltan datos", "Escribe el nombre y el dorsal del jugador."); return; } void addPlayer(name.trim(), number.trim(), position); setName(""); setNumber(""); setPosition("Ala"); };
  const login = () => { if (!email.trim() || !password) { Alert.alert("Faltan datos", "Escribe el email y la contraseña del administrador."); return; } void loginAdmin(email.trim(), password); };
  const reset = () => Alert.alert("Reiniciar temporada", "Se borrarán partidos, puntos, goles, asistencias y MVP. La plantilla se conservará.", [{ text: "Cancelar", style: "cancel" }, { text: "Reiniciar", style: "destructive", onPress: () => { void resetSeason(); } }]);

  return <Screen testID="admin-screen"><Header kicker="GESTIÓN DE PLANTILLA" title="Administración" subtitle="El equipo edita; la peña consulta en tiempo real." icon="account-group-outline" />
    {cloudStatus === "missing" ? <EmptyState icon="cloud-off-outline" title="Conecta Supabase" message="Añade la URL pública y la clave anon en las variables EXPO_PUBLIC_SUPABASE para activar la sincronización." /> : !isAdmin ? <LoginCard email={email} password={password} setEmail={setEmail} setPassword={setPassword} onLogin={login} colors={colors} styles={styles} /> : <>
      <View style={[styles.adminBar, { backgroundColor: colors.brandTertiary, borderColor: colors.borderStrong }]}><MaterialCommunityIcons name="shield-check" size={19} color={colors.brandPrimary} /><Text style={[styles.adminBarText, { color: colors.onSurface }]}>Modo Administrador activo</Text><Pressable testID="admin-logout" onPress={() => { void logoutAdmin(); }}><Text style={[styles.adminLogout, { color: colors.brandPrimary }]}>Salir</Text></Pressable></View>
      <KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : "height"}>
        <SectionTitle title="Añadir jugador" action="NUEVO" />
        <View style={[sharedStyles.card, { backgroundColor: colors.surfaceSecondary, borderColor: colors.border }]}>
          <Text style={[sharedStyles.fieldLabel, { color: colors.muted }]}>Nombre</Text><TextInput testID="player-name" value={name} onChangeText={setName} placeholder="Ej. Dani García" placeholderTextColor={colors.muted} style={[sharedStyles.input, styles.formInput, { color: colors.onSurface, backgroundColor: colors.surfaceTertiary, borderColor: colors.border }]} />
          <Text style={[sharedStyles.fieldLabel, styles.formLabel, { color: colors.muted }]}>Dorsal</Text><TextInput testID="player-number" value={number} onChangeText={setNumber} keyboardType="number-pad" placeholder="10" placeholderTextColor={colors.muted} style={[sharedStyles.input, styles.formInput, { color: colors.onSurface, backgroundColor: colors.surfaceTertiary, borderColor: colors.border }]} />
          <Text style={[sharedStyles.fieldLabel, styles.formLabel, { color: colors.muted }]}>Posición</Text><View style={styles.positionGrid}>{positions.map((item) => <Pressable testID={`position-${item}`} key={item} accessibilityRole="button" onPress={() => setPosition(item)} style={[styles.positionChip, { backgroundColor: position === item ? colors.brandTertiary : colors.surfaceTertiary, borderColor: position === item ? colors.borderStrong : colors.border }]}><Text style={{ color: position === item ? colors.onBrandTertiary : colors.muted, fontSize: 12, fontWeight: "800" }}>{item}</Text></Pressable>)}</View>
          <View style={styles.addButton}><PrimaryButton testID="add-player" label="Añadir a la plantilla" icon="account-plus-outline" onPress={add} /></View>
        </View>
      </KeyboardAvoidingView>
    </>}
    <SectionTitle title="Plantilla" action={`${state.players.length} JUGADORES`} />
    {state.players.length === 0 ? <EmptyState icon="account-multiple-outline" title="Todavía no hay jugadores" message={isAdmin ? "Añade el primer jugador con el formulario de arriba." : "El administrador todavía no ha añadido jugadores."} /> : <View style={[styles.rosterCard, { backgroundColor: colors.surfaceSecondary, borderColor: colors.border }]}>{state.players.map((player) => <View key={player.id} style={styles.rosterRow}><View style={[styles.rosterNumber, { backgroundColor: colors.surfaceTertiary }]}><Text style={[styles.rosterNumberText, { color: colors.brandSecondary }]}>{player.number}</Text></View><View style={styles.rosterCopy}><Text style={[styles.rosterName, { color: colors.onSurface }]}>{player.name}</Text><Text style={[styles.rosterPosition, { color: colors.muted }]}>{player.position}</Text></View>{isAdmin ? <Pressable testID={`delete-player-${player.id}`} accessibilityRole="button" onPress={() => Alert.alert("Eliminar jugador", `¿Quieres quitar a ${player.name} de la plantilla?`, [{ text: "Cancelar", style: "cancel" }, { text: "Eliminar", style: "destructive", onPress: () => { void removePlayer(player.id); } }])} style={styles.deleteButton}><MaterialCommunityIcons name="trash-can-outline" size={20} color={colors.error} /></Pressable> : null}</View>)}</View>}
    {isAdmin ? <><SectionTitle title="Temporada" /><View style={[styles.resetCard, { backgroundColor: colors.surfaceSecondary, borderColor: colors.border }]}><View style={[styles.resetIcon, { backgroundColor: colors.surfaceTertiary }]}><MaterialCommunityIcons name="restart" size={22} color={colors.warning} /></View><View style={styles.resetCopy}><Text style={[styles.resetTitle, { color: colors.onSurface }]}>Reiniciar estadísticas</Text><Text style={[styles.resetText, { color: colors.muted }]}>Borra el historial cloud y conserva la plantilla.</Text></View><Pressable testID="reset-season" accessibilityRole="button" onPress={reset} style={[styles.resetButton, { borderColor: colors.warning }]}><Text style={{ color: colors.warning, fontWeight: "900", fontSize: 12 }}>REINICIAR</Text></Pressable></View></> : null}
  </Screen>;
}

function LoginCard({ email, password, setEmail, setPassword, onLogin, colors, styles }: { email: string; password: string; setEmail: (value: string) => void; setPassword: (value: string) => void; onLogin: () => void; colors: ReturnType<typeof useTheme>["colors"]; styles: ReturnType<typeof useStyles> }) {
  return <View style={[sharedStyles.card, styles.loginCard, { backgroundColor: colors.surfaceSecondary, borderColor: colors.border }]}><View style={styles.loginIcon}><MaterialCommunityIcons name="shield-lock-outline" size={25} color={colors.brandPrimary} /></View><Text style={[styles.loginTitle, { color: colors.onSurface }]}>Acceso administrador</Text><Text style={[styles.loginText, { color: colors.muted }]}>Los jugadores pueden consultar y marcar asistencia. Solo tu cuenta puede editar.</Text><Text style={[sharedStyles.fieldLabel, { color: colors.muted }]}>Email</Text><TextInput testID="admin-email" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="tu@email.com" placeholderTextColor={colors.muted} style={[sharedStyles.input, { color: colors.onSurface, backgroundColor: colors.surfaceTertiary, borderColor: colors.border }]} /><Text style={[sharedStyles.fieldLabel, styles.formLabel, { color: colors.muted }]}>Contraseña</Text><TextInput testID="admin-password" secureTextEntry value={password} onChangeText={setPassword} placeholder="Contraseña" placeholderTextColor={colors.muted} style={[sharedStyles.input, { color: colors.onSurface, backgroundColor: colors.surfaceTertiary, borderColor: colors.border }]} /><View style={styles.loginButton}><PrimaryButton testID="admin-login" label="Entrar como administrador" icon="login" onPress={onLogin} /></View><Text style={[styles.loginHint, { color: colors.muted }]}>Usa la cuenta creada en Supabase. La contraseña inicial acordada es 1234.</Text></View>;
}

const useStyles = makeStyles((colors) => ({
  loginCard: { marginHorizontal: 18 }, loginIcon: { width: 46, height: 46, borderRadius: 14, backgroundColor: colors.brandTertiary, alignItems: "center", justifyContent: "center", marginBottom: 12 }, loginTitle: { fontSize: 19, fontWeight: "900" }, loginText: { fontSize: 13, lineHeight: 19, marginTop: 5, marginBottom: 18 }, loginButton: { marginTop: 18 }, loginHint: { fontSize: 11, lineHeight: 16, marginTop: 11 }, adminBar: { marginHorizontal: 18, marginBottom: 12, minHeight: 48, paddingHorizontal: 12, borderWidth: 1, borderRadius: 12, flexDirection: "row", alignItems: "center", gap: 8 }, adminBarText: { flex: 1, fontSize: 13, fontWeight: "800" }, adminLogout: { fontSize: 13, fontWeight: "900" }, formInput: { marginBottom: 0 }, formLabel: { marginTop: 14 }, positionGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, positionChip: { minHeight: 42, paddingHorizontal: 12, borderRadius: 10, borderWidth: 1, alignItems: "center", justifyContent: "center" }, addButton: { marginTop: 18 }, rosterCard: { marginHorizontal: 18, borderRadius: 16, borderWidth: 1, paddingHorizontal: 14 }, rosterRow: { minHeight: 68, flexDirection: "row", alignItems: "center", borderBottomWidth: 1, borderBottomColor: colors.divider, gap: 11 }, rosterNumber: { width: 38, height: 38, borderRadius: 10, alignItems: "center", justifyContent: "center" }, rosterNumberText: { fontSize: 15, fontWeight: "900" }, rosterCopy: { flex: 1 }, rosterName: { fontSize: 14, fontWeight: "800" }, rosterPosition: { fontSize: 12, marginTop: 3 }, deleteButton: { width: 44, height: 44, alignItems: "center", justifyContent: "center" }, resetCard: { marginHorizontal: 18, borderRadius: 16, borderWidth: 1, padding: 14, flexDirection: "row", alignItems: "center", gap: 10 }, resetIcon: { width: 40, height: 40, borderRadius: 12, alignItems: "center", justifyContent: "center" }, resetCopy: { flex: 1 }, resetTitle: { fontSize: 14, fontWeight: "900" }, resetText: { fontSize: 11, lineHeight: 16, marginTop: 3 }, resetButton: { minHeight: 38, borderWidth: 1, borderRadius: 9, paddingHorizontal: 9, justifyContent: "center" },
}));