import { MaterialCommunityIcons } from "@expo/vector-icons";
import { useState } from "react";
import { Alert, Pressable, Text, View } from "react-native";

import { EmptyState, Header, PrimaryButton, Screen, SectionTitle } from "@/src/components/screen";
import { useApp } from "@/src/store";
import { makeStyles, useTheme } from "@/src/theme";

export default function MatchScreen() {
  const { state, hydrated, setAssignment, setScore, setStat, setMvp, finalizeMatch } = useApp();
  const { colors } = useTheme();
  const styles = useStyles();
  const [mvpOpen, setMvpOpen] = useState(false);
  const confirmed = state.players.filter((player) => player.attendance === "yes");
  const green = confirmed.filter((player) => state.assignments[player.id] === "green");
  const yellow = confirmed.filter((player) => state.assignments[player.id] === "yellow");
  const assigned = confirmed.filter((player) => state.assignments[player.id]);
  const mvp = confirmed.find((player) => player.id === state.mvpId);

  if (!hydrated) return <Screen scroll={false}><View style={styles.center}><Text style={styles.loading}>Cargando el partido…</Text></View></Screen>;
  if (confirmed.length === 0) return <Screen testID="match-screen"><Header kicker="JORNADA SEMANAL" title="Partido" subtitle="Reparte equipos y registra las estadísticas del encuentro." icon="soccer-field" /><EmptyState icon="account-check-outline" title="Confirma la asistencia primero" message="Ve a Convocatoria y marca quién viene para poder crear los equipos." /></Screen>;

  return <Screen testID="match-screen">
    <Header kicker="JORNADA SEMANAL" title="Partido" subtitle="Reparte equipos y registra las estadísticas del encuentro." icon="soccer-field" />
    <View style={[styles.scoreCard, { backgroundColor: colors.surfaceSecondary, borderColor: colors.border }]}>
      <Text style={[styles.scoreKicker, { color: colors.muted }]}>MARCADOR FINAL</Text>
      <View style={styles.scoreRow}><ScoreTeam color={colors.brandPrimary} label="VERDE" score={state.scoreGreen} onMinus={() => setScore("green", -1)} onPlus={() => setScore("green", 1)} styles={styles} /><Text style={[styles.scoreDash, { color: colors.muted }]}>:</Text><ScoreTeam color={colors.brandSecondary} label="AMARILLO" score={state.scoreYellow} onMinus={() => setScore("yellow", -1)} onPlus={() => setScore("yellow", 1)} styles={styles} /></View>
    </View>
    <SectionTitle title="Reparto de equipos" action={`${assigned.length}/${confirmed.length} ASIGNADOS`} />
    <View style={[styles.assignmentCard, { backgroundColor: colors.surfaceSecondary, borderColor: colors.border }]}>
      <View style={styles.teamHeader}><View style={[styles.dot, { backgroundColor: colors.brandPrimary }]} /><Text style={[styles.teamHeaderText, { color: colors.onSurface }]}>Verde</Text><Text style={[styles.teamCount, { color: colors.muted }]}>{green.length}</Text><View style={[styles.dot, { backgroundColor: colors.brandSecondary, marginLeft: 18 }]} /><Text style={[styles.teamHeaderText, { color: colors.onSurface }]}>Amarillo</Text><Text style={[styles.teamCount, { color: colors.muted }]}>{yellow.length}</Text></View>
      {confirmed.map((player) => <View key={player.id} style={styles.assignRow}><View style={styles.assignName}><Text style={[styles.assignPlayer, { color: colors.onSurface }]}>{player.name}</Text><Text style={[styles.assignPosition, { color: colors.muted }]}>#{player.number} · {player.position}</Text></View><View style={styles.assignActions}><Pressable accessibilityRole="button" onPress={() => setAssignment(player.id, "green")} style={[styles.teamButton, { backgroundColor: state.assignments[player.id] === "green" ? colors.brandPrimary : colors.surfaceTertiary }]}><Text style={{ color: state.assignments[player.id] === "green" ? colors.onBrandPrimary : colors.muted, fontSize: 11, fontWeight: "900" }}>VERDE</Text></Pressable><Pressable accessibilityRole="button" onPress={() => setAssignment(player.id, "yellow")} style={[styles.teamButton, { backgroundColor: state.assignments[player.id] === "yellow" ? colors.brandSecondary : colors.surfaceTertiary }]}><Text style={{ color: state.assignments[player.id] === "yellow" ? colors.onBrandSecondary : colors.muted, fontSize: 11, fontWeight: "900" }}>AMAR.</Text></Pressable></View></View>)}
    </View>
    <SectionTitle title="Goles y asistencias" action="TOCA + PARA SUMAR" />
    <View style={[styles.statsCard, { backgroundColor: colors.surfaceSecondary, borderColor: colors.border }]}>{assigned.length === 0 ? <Text style={[styles.helper, { color: colors.muted }]}>Asigna jugadores a un equipo para registrar sus estadísticas.</Text> : assigned.map((player) => { const stat = state.stats[player.id] ?? { goals: 0, assists: 0 }; return <View key={player.id} style={styles.statRow}><View style={styles.statName}><Text style={[styles.assignPlayer, { color: colors.onSurface }]}>{player.name}</Text><Text style={[styles.assignPosition, { color: colors.muted }]}>{state.assignments[player.id] === "green" ? "Equipo Verde" : "Equipo Amarillo"}</Text></View><StatControl icon="soccer" label="Goles" value={stat.goals} onMinus={() => setStat(player.id, "goals", -1)} onPlus={() => setStat(player.id, "goals", 1)} colors={colors} styles={styles} /><StatControl icon="shoe-print" label="Asist." value={stat.assists} onMinus={() => setStat(player.id, "assists", -1)} onPlus={() => setStat(player.id, "assists", 1)} colors={colors} styles={styles} /></View>; })}</View>
    <SectionTitle title="MVP del partido" action="+1 TROFEO" />
    <View style={[styles.mvpWrap, { backgroundColor: colors.surfaceSecondary, borderColor: colors.border }]}><Pressable disabled={state.finalized} accessibilityRole="button" onPress={() => setMvpOpen((open) => !open)} style={[styles.mvpSelect, { backgroundColor: colors.surfaceTertiary, borderColor: colors.border }]}><MaterialCommunityIcons name="trophy-outline" color={colors.brandSecondary} size={20} /><Text style={[styles.mvpValue, { color: mvp ? colors.onSurface : colors.muted }]}>{mvp?.name ?? "Seleccionar jugador"}</Text><MaterialCommunityIcons name={mvpOpen ? "chevron-up" : "chevron-down"} color={colors.muted} size={20} /></Pressable>{mvpOpen && !state.finalized ? <View style={[styles.mvpList, { borderColor: colors.border, backgroundColor: colors.surfaceTertiary }]}>{confirmed.map((player) => <Pressable key={player.id} onPress={() => { setMvp(player.id); setMvpOpen(false); }} style={styles.mvpOption}><Text style={[styles.mvpOptionText, { color: colors.onSurface }]}>{player.name}</Text><Text style={[styles.assignPosition, { color: colors.muted }]}>#{player.number}</Text></Pressable>)}</View> : null}</View>
    <PrimaryButton label={state.finalized ? "Partido finalizado" : "Finalizar partido"} icon={state.finalized ? "check-decagram" : "flag-checkered"} disabled={state.finalized || green.length === 0 || yellow.length === 0} onPress={() => { finalizeMatch(); Alert.alert("Partido finalizado", "Los puntos y estadísticas ya están en la clasificación."); }} />
    {!state.finalized && (green.length === 0 || yellow.length === 0) ? <Text style={[styles.footerHint, { color: colors.muted }]}>Necesitas al menos un jugador en cada equipo.</Text> : null}
  </Screen>;
}

function ScoreTeam({ color, label, score, onMinus, onPlus, styles }: { color: string; label: string; score: number; onMinus: () => void; onPlus: () => void; styles: ReturnType<typeof useStyles> }) {
  return <View style={styles.scoreTeam}><Text style={[styles.scoreTeamLabel, { color }]}>{label}</Text><Text style={styles.scoreNumber}>{score}</Text><View style={styles.scoreActions}><Pressable accessibilityRole="button" onPress={onMinus} style={styles.scoreButton}><Text style={styles.scoreButtonText}>−</Text></Pressable><Pressable accessibilityRole="button" onPress={onPlus} style={[styles.scoreButton, { backgroundColor: color }]}><Text style={styles.scoreButtonPlus}>+</Text></Pressable></View></View>;
}

function StatControl({ icon, label, value, onMinus, onPlus, colors, styles }: { icon: keyof typeof MaterialCommunityIcons.glyphMap; label: string; value: number; onMinus: () => void; onPlus: () => void; colors: ReturnType<typeof useTheme>["colors"]; styles: ReturnType<typeof useStyles> }) {
  return <View style={styles.statControl}><View style={styles.statLabel}><MaterialCommunityIcons name={icon} color={colors.brandPrimary} size={14} /><Text style={[styles.statLabelText, { color: colors.muted }]}>{label}</Text></View><View style={styles.statCounter}><Pressable onPress={onMinus} accessibilityRole="button"><Text style={[styles.counterButton, { color: colors.muted }]}>−</Text></Pressable><Text style={[styles.statValue, { color: colors.onSurface }]}>{value}</Text><Pressable onPress={onPlus} accessibilityRole="button"><Text style={[styles.counterButton, { color: colors.brandPrimary }]}>+</Text></Pressable></View></View>;
}

const useStyles = makeStyles((colors) => ({
  center: { flex: 1, alignItems: "center", justifyContent: "center" }, loading: { color: colors.muted, fontSize: 15 },
  scoreCard: { marginHorizontal: 18, borderRadius: 18, borderWidth: 1, padding: 16, marginBottom: 18 }, scoreKicker: { textAlign: "center", fontSize: 11, fontWeight: "900", letterSpacing: 1.2 }, scoreRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-around", marginTop: 12 }, scoreTeam: { alignItems: "center", flex: 1 }, scoreTeamLabel: { fontSize: 12, fontWeight: "900", letterSpacing: 1 }, scoreNumber: { color: colors.onSurface, fontSize: 48, fontWeight: "900", lineHeight: 55, marginTop: 2 }, scoreDash: { fontSize: 30, fontWeight: "900", marginTop: 20 }, scoreActions: { flexDirection: "row", gap: 8, marginTop: 4 }, scoreButton: { width: 38, height: 38, borderRadius: 11, backgroundColor: colors.surfaceTertiary, alignItems: "center", justifyContent: "center" }, scoreButtonText: { color: colors.muted, fontSize: 24, lineHeight: 28 }, scoreButtonPlus: { color: colors.onBrandPrimary, fontSize: 23, lineHeight: 27 },
  assignmentCard: { marginHorizontal: 18, borderRadius: 16, borderWidth: 1, padding: 14, marginBottom: 8 }, teamHeader: { flexDirection: "row", alignItems: "center", paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: colors.divider }, dot: { width: 9, height: 9, borderRadius: 5, marginRight: 6 }, teamHeaderText: { fontSize: 13, fontWeight: "900" }, teamCount: { fontSize: 13, fontWeight: "800", marginLeft: 5 }, assignRow: { minHeight: 62, flexDirection: "row", alignItems: "center", borderBottomWidth: 1, borderBottomColor: colors.divider }, assignName: { flex: 1 }, assignPlayer: { fontSize: 14, fontWeight: "800" }, assignPosition: { fontSize: 11, marginTop: 3 }, assignActions: { flexDirection: "row", gap: 5 }, teamButton: { minWidth: 54, height: 38, borderRadius: 9, alignItems: "center", justifyContent: "center" },
  statsCard: { marginHorizontal: 18, borderRadius: 16, borderWidth: 1, paddingHorizontal: 13, marginBottom: 8 }, helper: { paddingVertical: 22, fontSize: 13, textAlign: "center" }, statRow: { minHeight: 70, flexDirection: "row", alignItems: "center", borderBottomWidth: 1, borderBottomColor: colors.divider, gap: 7 }, statName: { flex: 1 }, statControl: { alignItems: "center" }, statLabel: { flexDirection: "row", alignItems: "center", gap: 3 }, statLabelText: { fontSize: 10, fontWeight: "800" }, statCounter: { flexDirection: "row", alignItems: "center", gap: 3, marginTop: 1 }, counterButton: { fontSize: 22, fontWeight: "700", paddingHorizontal: 5 }, statValue: { fontSize: 16, fontWeight: "900", minWidth: 16, textAlign: "center" },
  mvpWrap: { marginHorizontal: 18, borderRadius: 16, borderWidth: 1, padding: 12, marginBottom: 18 }, mvpSelect: { minHeight: 48, borderRadius: 10, borderWidth: 1, flexDirection: "row", alignItems: "center", paddingHorizontal: 12, gap: 9 }, mvpValue: { flex: 1, fontSize: 14, fontWeight: "700" }, mvpList: { borderWidth: 1, borderRadius: 10, marginTop: 7, overflow: "hidden" }, mvpOption: { minHeight: 48, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: colors.divider }, mvpOptionText: { fontSize: 14, fontWeight: "700" }, footerHint: { textAlign: "center", fontSize: 12, marginTop: 9, marginBottom: 5 },
}));